package DAL;
// Generated 3-dec-2014 14:34:15 by Hibernate Tools 3.6.0



/**
 * TblCursist generated by hbm2java
 */
public class Cursist  implements java.io.Serializable {


     private int cursistId;
     private String naam;
     private String email;
     private String phone;
     //private int moduleId;

    public Cursist() {
    }

    public Cursist(String naam, String email, String phone, int moduleId) {
       this.naam = naam;
       this.email = email;
       this.phone = phone;
       //this.moduleId = moduleId;
    }

    public Cursist(int cursistId, String naam, String email, String phone) {
        this.cursistId = cursistId;
        this.naam = naam;
        this.email = email;
        this.phone = phone;
    }   
   
    public Integer getCursistId() {
        return this.cursistId;
    }
    
    public void setCursistId(Integer cursistId) {
        this.cursistId = cursistId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

//    public int getModuleId() {
//        return this.moduleId;
//    }
//    
//    public void setModuleId(int moduleId) {
//        this.moduleId = moduleId;
//    }
    @Override
    public String toString() {
        return naam; //To change body of generated methods, choose Tools | Templates.
    }

    


}


