package DAL;
// Generated 3-dec-2014 14:34:15 by Hibernate Tools 3.6.0



/**
 * TblDocent generated by hbm2java
 */
public class TblDocent  implements java.io.Serializable {


     private Integer docentId;
     private String naam;
     private String email;
     private String phone;

    public TblDocent() {
    }

    public TblDocent(String naam, String email, String phone) {
       this.naam = naam;
       this.email = email;
       this.phone = phone;
    }
   
    public Integer getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(Integer docentId) {
        this.docentId = docentId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


