package DAL;
// Generated 3-dec-2014 14:34:15 by Hibernate Tools 3.6.0



/**
 * TblModule generated by hbm2java
 */
public class TblModule  implements java.io.Serializable {


     private Integer moduleId;
     private String naam;
     private int lokaalId;
     private int docentId;
     private int cursistId;

    public TblModule() {
    }

    public TblModule(String naam, int lokaalId, int docentId, int cursistId) {
       this.naam = naam;
       this.lokaalId = lokaalId;
       this.docentId = docentId;
       this.cursistId = cursistId;
    }
   
    public Integer getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }
    public int getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(int docentId) {
        this.docentId = docentId;
    }
    public int getCursistId() {
        return this.cursistId;
    }
    
    public void setCursistId(int cursistId) {
        this.cursistId = cursistId;
    }




}


